### ISSUE TITLE
Flood protection

### ISSUE THREAD

**Issue by Mostey** [Mostey/epvpapi#28]
Some days ago, elitepvpers set up a flood protection that is driving me nuts already - IPs are going to be banned if a certain amount of HTTP requests is performed, even if you only update data using HTTP GET requests.

* Add the UserAgent HTTP header for both POST and GET requests since that may increase the amount of allowed requests 
* Catch 403 forbidden http errors and wrap them into an own exception that occurs if one's IP has been banned for flooding
* Consider implementing some kind of protection that counts requests and blocks after a certain amount of requests has been performed (by throwing an exception) for preventing the IP ban.

**Comment by sharpshadow** [comment]
If you have some numbers just tell us. I thought the cloudfare solution would have some positive impact on the request ammount, because you may have more controll over the estimated IP-Block time and how many requests you can make.
Perhaps you should add additionally to the 403 and counter a function which recognizes the 'checking browser' state.

For me the 0.1s timeout for all kind of requests to epvp is still working fine.
